import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Heart, Sparkles, Users, GraduationCap, Building2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Section } from "@/components/site/Section";
import { ImagePlaceholder } from "@/components/site/ImagePlaceholder";
import { Card } from "@/components/ui/card";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Instituto Cultural Sabá — Dança, cultura e impacto social" }, { name: "description", content: "Instituto Cultural Sabá: formação, visibilidade e oportunidades para jovens talentos da dança brasileira." }] }),
  component: Home,
});

function Home() {
  return <>
    <section className="relative overflow-hidden"><div className="container-x pt-16 md:pt-24 pb-20 md:pb-28 grid gap-12 lg:grid-cols-12 lg:items-end">
      <div className="lg:col-span-7"><p className="eyebrow">Instituto Cultural Sabá</p><h1 className="mt-6 text-5xl sm:text-6xl md:text-7xl leading-[0.98] text-foreground">O futuro da dança <em className="text-primary not-italic italic font-display">começa aqui.</em></h1><p className="mt-6 max-w-xl text-base md:text-lg text-muted-foreground leading-relaxed">Idealizado pela bailarina Marina Sabá, o Instituto Cultural Sabá fortalece a dança no Brasil e cria oportunidades para que jovens talentos sejam reconhecidos e celebrados.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/patrocinio">Seja patrocinador <ArrowRight className="ml-1 h-4 w-4" /></Link></Button><Button asChild size="lg" variant="outline"><Link to="/audicoes">Inscreva-se para audição</Link></Button><Button asChild size="lg" variant="ghost"><Link to="/programacao">Ver programação</Link></Button></div></div>
      <div className="lg:col-span-5 relative"><div className="grid grid-cols-2 gap-3"><ImagePlaceholder label="Ensaio" aspect="3/4" /><div className="flex flex-col gap-3 pt-8"><ImagePlaceholder label="Cena" aspect="1/1" /><ImagePlaceholder label="Bastidor" aspect="3/4" /></div></div><div className="absolute -bottom-6 -left-6 hidden md:block bg-saba-pink text-foreground px-5 py-4 rounded-lg shadow-lg max-w-[220px]"><p className="text-xs uppercase tracking-[0.18em] text-primary">Temporada</p><p className="mt-1 font-display text-xl leading-tight">Setembro · 2026</p><p className="mt-1 text-xs text-foreground/70">Belo Horizonte — MG</p></div></div>
    </div></section>

    <Section eyebrow="Nosso propósito" title="Movimento que dá visibilidade, coragem e futuro à dança brasileira." subtitle="O Instituto Cultural Sabá nasceu da experiência de Marina Sabá e da convicção de que a arte transforma vidas. Criamos espaço para a formação, a profissionalização e a valorização de jovens artistas."><div className="grid gap-6 md:grid-cols-3 md:items-start">{[{ icon: Sparkles, title: "Criação artística", text: "Espetáculos que celebram a técnica, a cultura e os talentos da dança brasileira.", className: "bg-primary border-primary md:-translate-y-4" }, { icon: GraduationCap, title: "Formação & oportunidades", text: "Suporte técnico e emocional para jovens artistas se desenvolverem profissionalmente.", className: "bg-saba-pink border-saba-pink md:translate-y-4" }, { icon: Heart, title: "Impacto social", text: "A arte como instrumento de transformação, acesso e empoderamento.", className: "bg-background border-foreground/20" }].map((f, index) => <Card key={f.title} className={`relative overflow-hidden rounded-[1.5rem] p-8 shadow-[8px_8px_0_var(--foreground)] ${f.className}`}><span className="absolute right-5 top-3 font-display text-6xl leading-none text-foreground/15">0{index + 1}</span><f.icon className="relative h-7 w-7 text-foreground" strokeWidth={1.5} /><h3 className="relative mt-8 text-3xl leading-[0.95]">{f.title}</h3><p className="relative mt-4 text-sm leading-relaxed text-foreground/75">{f.text}</p></Card>)}</div></Section>

    <Section tone="ink" eyebrow="O espetáculo em números" title="Uma produção que movimenta arte, trabalho e comunidade."><div className="grid gap-8 md:grid-cols-4">{[{ n: "30+", l: "bailarinos previstos no elenco" }, { n: "10+", l: "pessoas na equipe artística" }, { n: "40+", l: "pessoas na equipe técnica" }, { n: "1", l: "espetáculo exclusivo para escolas públicas" }].map((s) => <div key={s.l}><p className="font-display text-5xl md:text-6xl text-primary">{s.n}</p><p className="mt-2 text-sm text-foreground/70">{s.l}</p></div>)}</div></Section>

    <Section><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><ImagePlaceholder label="Cena de espetáculo" aspect="4/3" /><div><p className="eyebrow flex items-center gap-2"><Building2 className="h-3.5 w-3.5" /> Para empresas</p><h2 className="mt-4 text-4xl md:text-5xl">Patrocine e conecte sua marca à cultura brasileira.</h2><p className="mt-5 text-muted-foreground leading-relaxed">O espetáculo de dança Ballet Dom Quixote está aprovado pela Lei Federal de Incentivo à Cultura. Empresas tributadas pelo lucro real podem destinar até 4% do Imposto de Renda devido para apoiar o projeto.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild><Link to="/patrocinio">Quero conversar sobre patrocínio</Link></Button><Button asChild variant="outline"><Link to="/projeto">Conhecer o projeto</Link></Button></div></div></div></Section>

    <Section tone="muted"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="order-2 lg:order-1"><p className="eyebrow flex items-center gap-2"><Users className="h-3.5 w-3.5" /> Para artistas</p><h2 className="mt-4 text-4xl md:text-5xl">Audições abertas para bailarinos e artistas da cena.</h2><p className="mt-5 text-muted-foreground leading-relaxed">O elenco do Ballet Dom Quixote será formado por bailarinos profissionais selecionados por audição pública, além de convidados de renome internacional.</p><div className="mt-6"><Button asChild size="lg"><Link to="/audicoes">Fazer inscrição</Link></Button></div></div><div className="order-1 lg:order-2"><ImagePlaceholder label="Audição" aspect="4/3" /></div></div></Section>

    <Section><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><ImagePlaceholder label="Oficina em escola" aspect="4/3" /><div><p className="eyebrow flex items-center gap-2"><GraduationCap className="h-3.5 w-3.5" /> Para escolas públicas</p><h2 className="mt-4 text-4xl md:text-5xl">Cultura viva dentro da sala de aula.</h2><p className="mt-5 text-muted-foreground leading-relaxed">Como contrapartida social, o projeto prevê um espetáculo exclusivo para crianças de escolas públicas, com transporte e lanche para os estudantes.</p><div className="mt-6"><Button asChild><Link to="/escolas">Cadastrar minha escola</Link></Button></div></div></div></Section>

    <section className="bg-saba-pink text-foreground"><div className="container-x py-20 md:py-28 text-center max-w-3xl mx-auto"><p className="eyebrow">Fale com o Instituto</p><h2 className="mt-4 text-4xl md:text-6xl leading-tight">Vamos construir cultura juntos.</h2><p className="mt-5 text-foreground/70 leading-relaxed">Patrocinadores, artistas, escolas e parceiros institucionais: entre em contato e caminhe conosco nesta temporada.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild size="lg" className="bg-foreground text-saba-pink hover:bg-foreground/85"><Link to="/contato">Entrar em contato</Link></Button><Button asChild size="lg" variant="outline" className="bg-transparent border-foreground/35 text-foreground hover:bg-foreground/10"><Link to="/patrocinio">Ser patrocinador</Link></Button></div></div></section>
  </>;
}
