import { createFileRoute, Link } from "@tanstack/react-router";
import { Section } from "@/components/site/Section";
import { ImagePlaceholder } from "@/components/site/ImagePlaceholder";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/sobre")({
  head: () => ({ meta: [{ title: "Instituto e projeto — Instituto Cultural Sabá" }, { name: "description", content: "Conheça o Instituto Cultural Sabá, Marina Sabá e o projeto Ballet Dom Quixote." }] }),
  component: Sobre,
});

function Sobre() {
  return <>
    <Section eyebrow="O Instituto" title={<>O futuro da dança <em className="italic font-display text-primary not-italic">começa aqui.</em></>}>
      <div className="grid gap-12 md:grid-cols-5 items-start"><div className="md:col-span-2"><ImagePlaceholder label="Marina Sabá" aspect="4/5" /></div><div className="md:col-span-3 space-y-5 text-muted-foreground leading-relaxed">
        <p>O Instituto Cultural Sabá nasceu da visão de Marina Sabá para fortalecer a dança no Brasil, dar visibilidade aos talentos locais e criar oportunidades de profissionalização para jovens artistas.</p>
        <p>O Instituto responde à carência de oportunidades para bailarinos brasileiros em um mercado marcado por influências estrangeiras. Sua atuação busca oferecer suporte técnico e emocional, promover intercâmbio cultural e valorizar a dança nacional.</p>
        <blockquote className="border-l-4 border-primary pl-5 font-display text-2xl leading-snug text-foreground">“É preciso dar visibilidade e coragem aos jovens para a dança continuar transformando vidas.”</blockquote>
      </div></div>
    </Section>
    <Section tone="muted" eyebrow="A idealizadora" title="Marina Sabá."><div className="max-w-4xl space-y-5 text-muted-foreground leading-relaxed"><p>Marina Sabá é bailarina, empresária, advogada e pós-graduanda em direito cultural pela PUC Minas. Fundadora da Boutique 48, iniciou sua formação em Belo Horizonte pela metodologia da Royal Academy of Dance (RAD).</p><p>Representou o Brasil nas finais do Youth America Grand Prix, em Nova York; conquistou o primeiro lugar no Tanzolymp em 2018 e o segundo lugar em 2023; foi finalista do World Ballet Competition, entre as 12 melhores bailarinas, em 2018; e foi indicada como Melhor Bailarina de Minas Gerais em 2022.</p><p>Interpretou Kitri em <em>Dom Quixote</em>, Giselle em <em>Giselle</em> e a Fada Açucarada em <em>O Quebra-Nozes</em>. Sua trajetória inclui ballet clássico, dança contemporânea, jazz e sapateado irlandês.</p><blockquote className="border-l-4 border-primary pl-5 font-display text-2xl leading-snug text-foreground">“Dançar para mim é um estilo de vida [...] é sonhar, viver emoções que só os privilegiados podem sentir.”</blockquote></div></Section>
    <Section eyebrow="O projeto" title="Ballet Dom Quixote."><div className="grid gap-10 lg:grid-cols-2 items-start"><div className="space-y-5 text-muted-foreground leading-relaxed"><Badge variant="secondary" className="rounded-full">PRONAC 255925 · Aprovado e publicado</Badge><p>Remontagem do grande clássico do ballet de repertório em Belo Horizonte, o projeto preserva e celebra a obra, ao mesmo tempo em que busca democratizar o acesso à arte.</p><p>O elenco será formado por bailarinos profissionais selecionados por audição pública e convidados de renome internacional, favorecendo oportunidade de trabalho e intercâmbio cultural.</p><p><strong className="text-foreground">Previsão:</strong> setembro de 2026, em teatro com capacidade a partir de 1.000 lugares. O projeto inclui orquestra convidada, noite de abertura, exposição multicultural, geração de emprego e envolvimento da comunidade acadêmica.</p></div><ImagePlaceholder label="Ballet Dom Quixote" aspect="4/3" /></div></Section>
    <Section tone="muted" eyebrow="Impacto social" title="Arte, trabalho e acesso."><div className="grid gap-6 md:grid-cols-3 md:items-start">{[{ n: "30+", t: "bailarinos", d: "Elenco previsto para a produção.", c: "bg-primary border-primary md:-translate-y-5" }, { n: "50+", t: "profissionais", d: "Equipes artística e técnica, além de fornecedores e especialistas.", c: "bg-saba-pink border-saba-pink md:translate-y-5" }, { n: "01", t: "escolas públicas", d: "Espetáculo exclusivo, transporte e lanche para crianças convidadas.", c: "bg-background border-foreground/25" }].map((b) => <div key={b.t} className={`relative min-h-80 overflow-hidden rounded-[1.75rem] border p-8 shadow-[9px_9px_0_var(--foreground)] ${b.c}`}><p className="font-display text-7xl leading-none tracking-[-0.08em] text-foreground sm:text-8xl">{b.n}</p><div className="absolute bottom-0 left-0 right-0 border-t border-foreground/15 bg-background/25 p-7"><p className="text-xs font-bold uppercase tracking-[0.14em] text-foreground/70">{b.t}</p><p className="mt-3 text-base font-medium leading-relaxed text-foreground/90">{b.d}</p></div></div>)}</div></Section>
    <Section><div className="rounded-2xl bg-saba-pink text-foreground p-10 md:p-16 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 shadow-[8px_8px_0_var(--foreground)]"><div className="max-w-xl"><h3 className="text-3xl md:text-4xl">Faça parte desse movimento.</h3><p className="mt-3 text-foreground/70">Apoie o Ballet Dom Quixote via Lei Rouanet e ajude a ampliar o acesso à dança.</p></div><Button asChild size="lg" className="bg-foreground text-saba-pink hover:bg-foreground/85"><Link to="/patrocinio">Seja patrocinador</Link></Button></div></Section>
  </>;
}
