/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProjetoRouteImport } from './routes/projeto'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as PatrocinioRouteImport } from './routes/patrocinio'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as EspetaculoRouteImport } from './routes/espetaculo'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as ElencoRouteImport } from './routes/elenco'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AudicoesRouteImport } from './routes/audicoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminRegistroTipoIdRouteImport } from './routes/admin.registro.$tipo.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoRoute = ProjetoRouteImport.update({
  id: '/projeto',
  path: '/projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinioRoute = PatrocinioRouteImport.update({
  id: '/patrocinio',
  path: '/patrocinio',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculoRoute = EspetaculoRouteImport.update({
  id: '/espetaculo',
  path: '/espetaculo',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const ElencoRoute = ElencoRouteImport.update({
  id: '/elenco',
  path: '/elenco',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AudicoesRoute = AudicoesRouteImport.update({
  id: '/audicoes',
  path: '/audicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistroTipoIdRoute = AdminRegistroTipoIdRouteImport.update({
  id: '/admin/registro/$tipo/$id',
  path: '/admin/registro/$tipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audicoes': typeof AudicoesRoute
  '/contato': typeof ContatoRoute
  '/elenco': typeof ElencoRoute
  '/escolas': typeof EscolasRoute
  '/espetaculo': typeof EspetaculoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/patrocinio': typeof PatrocinioRoute
  '/programacao': typeof ProgramacaoRoute
  '/projeto': typeof ProjetoRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/registro/$tipo/$id': typeof AdminRegistroTipoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audicoes': typeof AudicoesRoute
  '/contato': typeof ContatoRoute
  '/elenco': typeof ElencoRoute
  '/escolas': typeof EscolasRoute
  '/espetaculo': typeof EspetaculoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/patrocinio': typeof PatrocinioRoute
  '/programacao': typeof ProgramacaoRoute
  '/projeto': typeof ProjetoRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/registro/$tipo/$id': typeof AdminRegistroTipoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audicoes': typeof AudicoesRoute
  '/contato': typeof ContatoRoute
  '/elenco': typeof ElencoRoute
  '/escolas': typeof EscolasRoute
  '/espetaculo': typeof EspetaculoRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/patrocinio': typeof PatrocinioRoute
  '/programacao': typeof ProgramacaoRoute
  '/projeto': typeof ProjetoRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/registro/$tipo/$id': typeof AdminRegistroTipoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audicoes'
    | '/contato'
    | '/elenco'
    | '/escolas'
    | '/espetaculo'
    | '/patrocinadores'
    | '/patrocinio'
    | '/programacao'
    | '/projeto'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/registro/$tipo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audicoes'
    | '/contato'
    | '/elenco'
    | '/escolas'
    | '/espetaculo'
    | '/patrocinadores'
    | '/patrocinio'
    | '/programacao'
    | '/projeto'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/registro/$tipo/$id'
  id:
    | '__root__'
    | '/'
    | '/audicoes'
    | '/contato'
    | '/elenco'
    | '/escolas'
    | '/espetaculo'
    | '/patrocinadores'
    | '/patrocinio'
    | '/programacao'
    | '/projeto'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/registro/$tipo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudicoesRoute: typeof AudicoesRoute
  ContatoRoute: typeof ContatoRoute
  ElencoRoute: typeof ElencoRoute
  EscolasRoute: typeof EscolasRoute
  EspetaculoRoute: typeof EspetaculoRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PatrocinioRoute: typeof PatrocinioRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  ProjetoRoute: typeof ProjetoRoute
  SobreRoute: typeof SobreRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRegistroTipoIdRoute: typeof AdminRegistroTipoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto': {
      id: '/projeto'
      path: '/projeto'
      fullPath: '/projeto'
      preLoaderRoute: typeof ProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinio': {
      id: '/patrocinio'
      path: '/patrocinio'
      fullPath: '/patrocinio'
      preLoaderRoute: typeof PatrocinioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculo': {
      id: '/espetaculo'
      path: '/espetaculo'
      fullPath: '/espetaculo'
      preLoaderRoute: typeof EspetaculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elenco': {
      id: '/elenco'
      path: '/elenco'
      fullPath: '/elenco'
      preLoaderRoute: typeof ElencoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audicoes': {
      id: '/audicoes'
      path: '/audicoes'
      fullPath: '/audicoes'
      preLoaderRoute: typeof AudicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registro/$tipo/$id': {
      id: '/admin/registro/$tipo/$id'
      path: '/admin/registro/$tipo/$id'
      fullPath: '/admin/registro/$tipo/$id'
      preLoaderRoute: typeof AdminRegistroTipoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudicoesRoute: AudicoesRoute,
  ContatoRoute: ContatoRoute,
  ElencoRoute: ElencoRoute,
  EscolasRoute: EscolasRoute,
  EspetaculoRoute: EspetaculoRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PatrocinioRoute: PatrocinioRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  ProjetoRoute: ProjetoRoute,
  SobreRoute: SobreRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRegistroTipoIdRoute: AdminRegistroTipoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
